#!/usr/bin/env python3
"""Is the generated corpus like real code, or is it measuring its own shape?

`tool/order.py` builds a synthetic file per grammar - N small statements and one
large string literal - and the gate reads a **ratio** off it, which no amount of
unrepresentativeness can forge: both halves are the same generated bytes. But the
same construction also produced an **absolute** number that went on the board,
java at 14,796 ns/B, against 487.6 ns/B for real java out of `bench.py`. A 30x
self-discrepancy in one grammar is either that grammar's own business or a
property of the generator, and those want different things done about them.

So every corpus grammar is priced twice, on the same axis, side by side:

  **real** - the corpus file the rest of the repository measures over, inflated
  by repetition to the same target size the throughput axis uses. Same
  construction as `bench.input_for`, imported rather than restated.
  **made**  - the `many-then-one` half of the order pair for that grammar.

If the gap is one grammar's, that grammar is the story. If every grammar carries
it, then the synthetic table is measuring generated code and **every absolute
number taken off it owes that caveat** - while every ratio taken off it still
stands, because a ratio between two orderings of one generated file never
crossed the corpus boundary the caveat is about.

**A mended parse is not comparable to a whole one.** It did less work, so its
per-byte cost is a cost of a smaller job. Rows are marked, and the summary only
counts grammars that read *both* files whole.

This does not measure the admitted set. Per-position cost is governed by how far
the union walk runs, which is set by voice composition - one permissive member
surviving to end-of-file makes every pattern sharing its voice pay a walk to
end-of-file - and not by how many terminals are permitted. That was settled in
the scanner lane by mechanism; a correlation here would at best have found a
confound.

Exit 0 measured, 2 could not.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import NamedTuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bench import TARGET, scale  # noqa: E402
from order import BIN, ROOT, SHAPE, Price, build, ext, folio_for, price  # noqa: E402
from rung1 import pairs  # noqa: E402
from stamp import take  # noqa: E402

CORPUS = ROOT / "research" / "joinery" / "corpus"


class Row(NamedTuple):
    name: str
    real: Price | None
    made: Price

    @property
    def gap(self) -> float:
        """How much dearer the generated file is per byte than real code."""
        if not (self.real and self.real.per_byte):
            return 0.0
        return self.made.per_byte / self.real.per_byte

    @property
    def honest(self) -> bool:
        return bool(self.real and self.real.kind == "whole" == self.made.kind)


def corpora(name: str, leaf: str, work: Path) -> tuple[Path | None, Path]:
    """The two files this grammar is priced over. Neither construction lives
    here: the inflation is `bench.scale`, the generated half is `order.build`,
    and both are imported so a change to either is measured rather than missed."""
    src, real = CORPUS / leaf, None
    if src.exists():
        body = src.read_text(encoding="utf-8")
        n = max(1, -(-TARGET // max(len(body), 1)))
        real = work / f"real-{name}{src.suffix}"
        real.write_text(scale(name, body, n), encoding="utf-8")
    made = work / f"made-{name}.{ext(name)}"
    made.write_text(build(name)[0], encoding="utf-8")
    return real, made


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("verb", nargs="?", default="run", choices=("run", "list"))
    ap.add_argument("--grammar", action="append", help="just this one (repeatable)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    # The roster is the corpus's own README through rung1, narrowed to the
    # grammars `order.build` can spell. A language added to either is picked up
    # with nothing here to update.
    roster = [(n, leaf) for n, leaf in pairs() if n in {*SHAPE, "json"}]
    if args.grammar:
        roster = [(n, leaf) for n, leaf in roster if n in args.grammar]
    if args.verb == "list":
        print(f"{'grammar':<12}{'corpus file':<20}{'generated bytes':>16}")
        for n, leaf in roster:
            print(f"{n:<12}{leaf:<20}{len(build(n)[0]):>16,}")
        return 0
    if not BIN.exists():
        print(f"likeness: no binary at {BIN}; `zig build` first", file=sys.stderr)
        return 2

    work = ROOT / ".local" / "likeness"
    work.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, leaf in roster:
        folio = folio_for(name, work)
        if folio is None:
            print(f"likeness: {name}: not pinned here, skipped", file=sys.stderr)
            continue
        real_src, made_src = corpora(name, leaf, work)
        rows.append(Row(name, price(folio, real_src) if real_src else None, price(folio, made_src)))
        print(f"likeness: {name} done", file=sys.stderr)

    if args.json:
        print(json.dumps([{"grammar": r.name,
                           "real": r.real._asdict() if r.real else None,
                           "made": r.made._asdict(),
                           "gap": round(r.gap, 2), "honest": r.honest} for r in rows], indent=2))
        return 0

    print(f"\n{'grammar':<12}{'real ns/B':>11}{'made ns/B':>11}{'gap':>8}"
          f"{'real us/nd':>12}{'made us/nd':>12}  read")
    for r in sorted(rows, key=lambda r: -r.gap):
        real = f"{r.real.per_byte:,.0f}" if r.real else "-"
        rn = f"{r.real.per_node:.2f}" if r.real else "-"
        read = "both whole" if r.honest else f"real {r.real.kind if r.real else '-'} · made {r.made.kind}"
        print(f"{r.name:<12}{real:>11}{r.made.per_byte:>11,.0f}{r.gap:>7.0f}x"
              f"{rn:>12}{r.made.per_node:>12.2f}  {read}")

    good = [r for r in rows if r.honest]
    print(f"\n{len(good)} of {len(rows)} grammars read both files whole; the rest mended on real "
          f"code, which is less work than a whole parse and not the same job priced twice.")
    if len(good) >= 3:
        gaps = sorted(((r.gap, r.name) for r in good), reverse=True)
        lo, hi = gaps[-1][0], gaps[0][0]
        near = sum(1 for g, _ in gaps if g < 3)
        print(f"generated against real: {lo:.0f}x to {hi:.0f}x, worst {gaps[0][1]}, "
              f"{near} of {len(good)} inside 3x.")
        # Three answers, not two. A two-way call here would have to fall one way
        # or the other on a knife edge - the run this was written against sits at
        # 2 of 5 inside 3x with a third at 3.2 - and the honest shape is neither
        # pole: some grammars pay it and some do not.
        print("  -> " + (
            "not the generator: every grammar prices generated code within 3x of real code, "
            "so any outlier elsewhere is that grammar's own business. The absolute table stands."
            if near == len(good) else
            "the generator: it is dearer than real code for every grammar measured, so every "
            "ABSOLUTE number taken off it needs that caveat."
            if near == 0 else
            f"per-grammar, which is neither pole: {near} of {len(good)} price generated code "
            f"within 3x of real code and {len(good) - near} do not, worst {gaps[0][1]} at "
            f"{hi:.0f}x. So an absolute number off the generated table needs a PER-ROW caveat "
            f"rather than a blanket one, and no grammar's gap is evidence about another's."))
        print("     Ratios between two orderings of one generated file are unaffected either "
              "way - they never cross the boundary this measures.")
    print(take(BIN).line())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
